server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-43-201-40-23.ap-northeast-2.compute.amazonaws.com:3306/likelion-db
    username: root
    password: 12345678

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO